import React from "react";
import LocalizedStrings from "react-native-localization";
const strings = new LocalizedStrings({
  en: {
    // Global
    Submit: "Submit",
    Oops: "Oops",
    AddThumbnail: "Add thumbnail",
    Search: "Search",
    male: "Male",
    female: "Female",
    Edit: "Edit",
    Delete: "Delete",
    AddNow: "Add Now",
    Updated: "Updated!",
    AddMore: "Add more",

    AppStackCategories: "Categories",
    AppStackProfile: "Profile",
    AppStackCart: "Cart",
    AppStackHistory: "History",

    //OnboardingScreen.js
    onboardingDescription:
      " Tailoron is a premiere App for online custom tailoring. It is enriched with excellent features including unlimited customizers, online design and submission, email notifications, measurement submission for each order and a lot more.",
    onboardingDone: "Lets get started",
    onboardingheader: "We customize your personality",

    // SingnupScreen.js
    signupEmail: "Email",
    signupPassword: "Password",
    signupCpassword: "Confirm password",
    signupSignup: "Sign up",
    signupByregisteringconfirm:
      "By registering, you confirm that you accept our",
    signupTermsservice: " Terms of service",
    signupand: "and",
    signupPrivacyPolicy: "Privacy policy",
    signupHaveaccountsignin: "Have an account? Sign in",
    signupSignin: " Signin now",
    signupTermsserviceAlert: "Terms clicked!",

    //LoginScreen.js
    loginEmail: "Email address",
    loginPassword: "Password",
    loginSignIn: "Sign in",
    loginForgotpassword: "Forgot password?",
    loginNotmember: "Not a member yet?",
    loginRegister: " Register now",

    // forgetPassword.js
    forgetpasswordEmail: "Email",
    forgetpasswordresetnow: "Reset now",
    forgetpasswordHaveaccount: "Have an account? Sign in",
    forgetpasswordSignin: " Signin now",

    //ProfileScreen.js
    profileUpdated: "Profile updated!",
    profilePublishedsuccessfully: "Your profile has been published!",
    profileAddcompletedata: "Please add complete data.",
    profilefirst_name: "First name",
    profilelast_name: "Last name",
    profilePhone: "Phone no.",
    profileAddress: "Address",
    profileBillingShipping: "Billing & shipping detail:",
    profileCountry: "Country",
    profileCity: "City",
    profileState: "State",
    profileZip: "Zip code",
    profileEmail: "Email",
    profileUpdateProfie: "Update profile",
    profileAddproDet: "Add profile details",
    profileSetting: "Profile setting",

    // AddCategories.js
    categoriesAlreadyadded: "Category already added.",
    categoriesPleaseselect: "Please select a category",
    categoriesCategoryadded: "Category added!",
    categoriesAddedsuccessfully: "Your category has been added!",
    categoriesCategoryDeleted: "Success!",
    categoriesDeletedsuccessfully: "Updated successfully!",
    categoriesSomethingwrongpostfirestore:
      "Something went wrong with updating post to firestore.",
    categoriesPleaseinsertcompletedata: "Please insert complete data",
    categoriesSelectgender: "Select gender",
    categoriesAddcategories: "Add categories",
    categoriesSelectcategory: "Select category",
    categoriesAddmorecategories: "Not in list? add new category",
    categoriesAddtolist: "Add to list",
    categoriesPleaseselectcategories: "Please select a categories",
    categoriessavechanges: " Save changes",
    categoriesAlreadyaddedcategories: "Added categories",
    categoriesmeasurements: "measurements: ",
    categoriesAddsteps: "Add sub categories",
    categoriestitle: "Sub category title",
    categoriesdescription: "Sub category description",
    categoriesThumbnailast_name: "Thumbnail name",
    categoriesAddfullimage: "Add full image",
    categoriesGeneratelist: "Add to list",
    categoriesAddapparel_steps: "Add main categories",
    categoriesTitle: "Title",
    categoriesSelectmeasurements: "Select measurements",
    categoriesTypeheresearch: "Type here to search ...",
    categoriesSelectmeasurement: "Select measurements:",
    categoriesChoosemeasurements: "Choose measurements",
    categoriesAddnew: "Add new",
    categoriesDelete: "Delete",
    categoriesEdit: "Edit",

    // AddMeasurement.js
    addMeasurementadded: "Measurement added!",
    addMeasurementAddedsuccessfully: "measurements has been added!",
    addMeasurementPleaseaddcompletedata: "Please add complete data.",
    addMeasurementEditpressed: "Edit pressed",
    addMeasurementMygender: "My gender",
    addMeasurementMeasurementdeleted: "Measurement deleted!",
    addMeasurementmeasurementsdeletedsuccessfully:
      "measurements has been deleted!",
    addMeasurementAddmeasurement: "Add measurement",
    addMeasurementTitle: "Title",
    addMeasurementDescription: "Description",
    addMeasurementvideo_link: "Video link",
    addmeasurementselectsize: "Select size",
    addMeasurementWatchvideo: "Watch video",
    addmeasurementMeasureIn: "Measure in:",
    addmeasurementsizecm: "Size in (cm)",
    addmeasurementsizeinch: "Size in (inch)",

    // AddNewCategory.js
    addnewcategoryCategoryalreadyaddsamename:
      "Category already added with same name.",
    addnewcategoryCategoryadded: "Category added!",
    addnewcategoryCategoryaddedsuccessfully: "Category has been added!",
    addnewcategoryPleaseaddcompldata: "Please add complete data.",
    addnewcategoryAddnewcategory: "Add new category",
    addnewcategoryTitle: "Title",
    addnewcategoryCategorieslist: "Categories list",
    addnewcategoryEditcategory: "Edit category",
    addnewcategoryCategoriesupdate: "Categories updated",
    addnewcategoryupdatedcategory: "Category has been updated!",
    addnewcategoryCategoriesdelete: "Categories delete",
    addnewcategorydeletedcategory: "Category has been deleted!",

    // Cart.js
    cartOrderplaced: "Order placed!",
    cartOrderplacedsuccessfully: "Your order has been placed!",
    cartCart: "Cart",
    cartPending: "Pending",
    cartPrice: "Price:",
    cartViewdetails: "View details",
    cartOrderdetails: "Order details",
    cartfirst_name: "First name:",
    cartlast_name: "Last name:",
    cartphone_number: "Phone no:",
    cartAddress: "Address:",
    cartMeasurments: "Measurments:",
    cartProceedorder: "Proceed order",

    // Categories.js
    categoriesmainGreat: "Great",
    categoriesmainYounowadmin: "You are now the admin",
    categoriesmainNothanks: "No, thanks",
    categoriesmainYesproceed: "Yes, proceed",
    categoriesmainPayattention: "Pay attention !!!",
    categoriesmainDoyoumakeaccountadmin:
      "Do you Want to make this account as an admin account?",
    categoriesmainSelectcategory: "Start with your category ",
    categoriesmainBeyourowntailor: "Be your own tailor",
    categoriesmainSearch: "Захиалга хайх", // solison
    categoriesmainWhatyoulikecustomize: "Start your customizing here ",
    categoriesmainMen: "Миний захиалга", // Men->Minii zahialga
    categoriesmainWomen: "Нийт захиалга", //Women-> nit zahialga
    categoriesmainDashboard: "Dashboard",
    categoriesmainAddcategories: "Add category",
    categoriesmainAddmeasurment: "Add measurment",
    categoriesmainVieworders: "View orders",
    categoriesmainViewmessages: "View messages",
    categoriesmainLatestordersnoti: "Latest orders notifications:",
    categoriesmainYouGotOrderfrom: "You have got a new order from",
    categoriesmainNoOrderFound: "No order found",
    categoriesmainLatestChats: "Latest chats",
    categoriesmainNoChatsFound: "No chats found",
    categoriesmainOrderCompleted: "Order completed",
    categoriesmainTotalEarnings: "Total earnings",
    categoriesmainNewMessages: "New messages",
    categoriesmainOrderHistory: "Order history",
    categoriesmainView: "View",
    categoriesmainSetting: "settings",

    // CategoryDetail.js
    categorydetailAddcompletemeasurement:
      "Please add complete measurements under ",
    categorydetailSelectsubategory: "Please select sub categories data under ",
    categorydetailAdded: "Added",
    categorydetailCustomizer: "Customizer",
    categorydetailItemaddedcart: "Item added in the cart.",
    categorydetailRequiredmeasurement: "Required measurement:",
    categorydetailAddmeasurements: "Add measurement",
    categorydetailAddcart: "Add to cart",
    categorydetailTypeValue: "Type value here",
    categorydetailInstruction: "Instruction",
    categorydetailNoCustomizerAvailable: "No Customizer Available",

    // ChatScreen.js
    chatscreenHelpSupport: "Help & support",
    chatscreenEntermessage: "Enter message",

    // OrderHistory.js
    orderhistoryfirst_name: "First name:",
    orderhistorylast_name: "Last name:",
    orderhistoryPhone: "Phone no:",
    orderhistoryAddress: "Address:",
    orderhistoryContactSeller: "Contact seller:",
    orderhistoryChat: "Chat now",
    orderhistoryMeasurments: "Measurments:",
    orderhistoryHeader: "Order history",

    // OrderList.js
    orderlistID: "Order ID",
    orderlistfirst_name: "First name:",
    orderlistlast_name: "Last name:",
    orderlistPhone: "Phone no:",
    orderlistAddress: "Address:",
    orderlistPrice: "Price:",
    orderlistDate: "Date:",
    orderlistUpdatestatus: "Manage status:",
    orderlistMeasurments: "Measurments:",
    orderlistStatusUpdated: "Status updated!",
    orderlistStatusupdatedsuccessfully: "Order status has been updated!",
    orderlistHeader: "Order list",
    orderlistNothanks: "No, thanks",
    orderlistPayattention: "Pay attention !!!",
    orderlistPleaseUpdatestatusorder:
      "Please select an option below to update the status of this order:",
    orderlistProcessing: "Processing",
    orderlistCompleted: "Completed",
    orderlistCancelled: "Cancelled",
    orderlistPending: "Pending",
    orderlistCompleteMsg: "Order completed",
    orderlistOrderDetails: " Order details:",

    // Authprovider.js
    authPleaseaddproperly: "Please add the data properly.",
    authNouserrecordmaydeleted:
      "There is no user record corresponding to this identifier. The user may have been deleted.",
    authAddemail: "Please add email.",

    // settings.js
    settingHeading: "settings",
    settingcurrency: "currency Setting :",
    settingselectcurrency: "Select currency",
    settingsave: "Save",
    settingChangeLanguage: "Change Language",
    settingLanguages: "Languages",
    settingGeneralEmailsettings: "General Email settings",
    settingEmailSetting: "Email Setting :",
    settingAddLogo: "Add logo",
    settingapi_key: "API key",
    settingproduct_title: "Product title",
    settingOrderPlacedTemplate: "Order placed template",
    settingDynamicparams: "Dynamic params:",
    settingParamsOne: "%name%",
    settingParamsTwo: "%order_id%",
    settingParamsThree: "%category_id%",
    settingParamsName: "This will be use to show customer name",
    settingParamsorder_id: "This will be used to show order ID",
    settingParamsCategory: "This will be use to show category like suiting",
    settingEmailSubject: "Email Subject",
    settingEmailContent: "Email content",
    settingProcessingOrderTemplate: "Processing order template",
    settingCompleteOrderTemplate: "Complete order template",
    settingCancelledOrderTemplate: "Cancelled order template",
    settingPleaseSelectchangeanguage:
      "Please select an option below to change the language",
    settingselectedcurrency: "Selected currency :",
    settingselectedLanguage: "Selected Language :",

    cartNoReacordFound: "No record, drag to refresh",
    historyNoReacordFound: "No Record found",
    pendingOrder: "Pending orders",
    processingorders: "Processing orders",
    completedorders: "Completed orders",
    cancelledorders: "Cancelled orders",
  },
  tr: {
    Submit: "Gönder",
    Oops: "Hata",
    AddThumbnail: "Küçük resim ekle",
    Search: "Ara",
    male: "Erkek",
    female: "Kadın",
    Edit: "Düzenle",
    Delete: "Sil",
    AddNow: "Şimdi Ekle",
    Updated: "Güncellenmiş!",
    AddMore: "Daha ekle",

    AppStackCategories: "Kategoriler",
    AppStackProfile: "Profil",
    AppStackCart: "Araba",
    AppStackHistory: "Tarih",

    onboardingDescription:
      "Tailoron çevrimiçi özel dikme için bir gala App olduğunu. Bu, sınırsız özelleştirme araçları, çevrimiçi tasarım ve sunulması, e-posta bildirimleri, her sipariş ve çok daha fazlası için ölçüm sunulması dahil olmak üzere mükemmel özelliklere sahip zenginleştirilmiştir.",
    onboardingDone: "Hadi başlayalım",
    onboardingheader: "Kişiliğinizi özelleştiriyoruz",

    signupEmail: "E-posta",
    signupPassword: "Şifre",
    signupCpassword: "Şifreyi onayla",
    signupSignup: "Kaydolun",
    signupByregisteringconfirm:
      "Kayıt olarak, bizim şartlarımızı kabul ettiğinizi onaylamış olursunuz",
    signupTermsservice: " Hizmet Şartları",
    signupand: "ve",
    signupPrivacyPolicy: "Gizlilik ilkesi",
    signupHaveaccountsignin: "Hesabınız var mı? Oturum açın",
    signupSignin: " Şimdi oturum açın ",
    signupTermsserviceAlert: "Şartlar tıklandı!",

    loginEmail: "E-posta adresi",
    loginPassword: "Şifre",
    loginSignIn: "Giriş yap",
    loginForgotpassword: "Şifrenizi mi unuttunuz?",
    loginNotmember: "Henüz üye değil misiniz?",
    loginRegister: " Şimdi kaydolun",

    forgetpasswordEmail: "E-posta",
    forgetpasswordresetnow: "Şimdi sıfırla",
    forgetpasswordHaveaccount: "Hesabınız var mı? Oturum açın",
    forgetpasswordSignin: " Şimdi oturum açın ",

    profileUpdated: "Profil güncellendi!",
    profilePublishedsuccessfully: "Profiliniz yayınlandı!",
    profileAddcompletedata: "Lütfen tüm verileri ekleyin.",
    profilefirst_name: "Ad",
    profilelast_name: "Soyadı",
    profilePhone: "Telefon no.",
    profileAddress: "Adres",
    profileBillingShipping: "Faturalandırma ve nakliye detayı:",
    profileCountry: "Ülke",
    profileCity: "Şehir",
    profileState: "Durum",
    profileZip: "Posta kodu",
    profileEmail: "E-posta",
    profileUpdateProfie: "Profili güncelle",
    profileAddproDet: "Profil ayrıntılarını ekleyin",
    profileSetting: "Profil ayarı",

    categoriesAlreadyadded: "Kategori zaten eklendi.",
    categoriesPleaseselect: "Lütfen bir kategori seçin",
    categoriesCategoryadded: "Kategori eklendi!",
    categoriesAddedsuccessfully: "Kategoriniz eklendi!",
    categoriesCategoryDeleted: "Başarılı!",
    categoriesDeletedsuccessfully: "Başarıyla güncellendi!",
    categoriesSomethingwrongpostfirestore:
      "Gönderiyi firestore'a güncellerken bir şeyler ters gitti.",
    categoriesPleaseinsertcompletedata: "Lütfen tüm verileri giriniz",
    categoriesSelectgender: "Cinsiyet seçin",
    categoriesAddcategories: "Kategori ekle",
    categoriesSelectcategory: "Kategori seçin",
    categoriesAddmorecategories: "? Değil listedeki yeni kategori eklemek",
    categoriesAddtolist: "Listeye Ekle",
    categoriesPleaseselectcategories: "Lütfen bir kategori seçin",
    categoriessavechanges: " Değişiklikleri kaydet",
    categoriesAlreadyaddedcategories: "Eklenen kategoriler",
    categoriesmeasurements: "Ölçümler:",
    categoriesAddsteps: "Alt kategori ekle",
    categoriestitle: "Alt kategori başlığı",
    categoriesdescription: "Alt kategori açıklaması",
    categoriesThumbnailast_name: "Küçük resim adı",
    categoriesAddfullimage: "Tam resim ekle",
    categoriesGeneratelist: "Listeye Ekle",
    categoriesAddapparel_steps: "Ana kategori ekle",
    categoriesTitle: "Başlık",
    categoriesSelectmeasurements: "Ölçümleri seçin",
    categoriesTypeheresearch: "Aramak için buraya yazın ...",
    categoriesSelectmeasurement: "Ölçümleri seçin:",
    categoriesChoosemeasurements: "Ölçümleri seçin",
    categoriesAddnew: "Yeni ekle",
    categoriesDelete: "Sil",
    categoriesEdit: "Düzenle",

    addMeasurementadded: "Ölçüm eklendi!",
    addMeasurementAddedsuccessfully: "Ölçümler eklendi!",
    addMeasurementPleaseaddcompletedata: "Lütfen tüm verileri ekleyin.",
    addMeasurementEditpressed: "Düzenlemeye basıldı",
    addMeasurementMygender: "Cinsiyetim",
    addMeasurementMeasurementdeleted: "Ölçüm silindi!",
    addMeasurementmeasurementsdeletedsuccessfully: "Ölçümler silindi!",
    addMeasurementAddmeasurement: "Ölçüm ekle",
    addMeasurementTitle: "Başlık",
    addMeasurementDescription: "Açıklama",
    addMeasurementvideo_link: "Video bağlantısı",
    addmeasurementselectsize: "Boyut seç",
    addMeasurementWatchvideo: "Videoyu izle",
    addmeasurementMeasureIn: "Ölçü:",
    addmeasurementsizecm: "Boyut (cm)",
    addmeasurementsizeinch: "Boyut (inç)",

    addnewcategoryCategoryalreadyaddsamename:
      "Kategori zaten aynı adla eklendi.",
    addnewcategoryCategoryadded: "Kategori eklendi!",
    addnewcategoryCategoryaddedsuccessfully: "Kategori eklendi!",
    addnewcategoryPleaseaddcompldata: "Lütfen tüm verileri ekleyin.",
    addnewcategoryAddnewcategory: "Yeni kategori ekle",
    addnewcategoryTitle: "Başlık",
    addnewcategoryCategorieslist: "Kategoriler listesi",
    addnewcategoryEditcategory: "Kategoriyi düzenle",
    addnewcategoryCategoriesupdate: "Kategoriler güncellendi",
    addnewcategoryupdatedcategory: "Kategori güncellendi!",
    addnewcategoryCategoriesdelete: "Kategoriler silin",
    addnewcategorydeletedcategory: "Kategori silindi!",

    cartOrderplaced: "Sipariş verildi!",
    cartOrderplacedsuccessfully: "Siparişiniz verildi!",
    cartCart: "Sepet",
    cartPending: "Beklemede",
    cartPrice: "Fiyat:",
    cartViewdetails: "Ayrıntıları görüntüle",
    cartOrderdetails: "Sipariş ayrıntıları",
    cartfirst_name: "Ad:",
    cartlast_name: "Soyadı:",
    cartphone_number: "Telefon no:",
    cartAddress: "Adres:",
    cartMeasurments: " Ölçümler :",
    cartProceedorder: "Siparişi devam ettir ",

    categoriesmainGreat: "Harika",
    categoriesmainYounowadmin: "Artık yönetici sizsiniz",
    categoriesmainNothanks: "Hayır, teşekkürler",
    categoriesmainYesproceed: "Evet, devam edin",
    categoriesmainPayattention: "Dikkat edin !!!",
    categoriesmainDoyoumakeaccountadmin:
      "Bu hesabı yönetici hesabı yapmak istiyor musunuz?",
    categoriesmainSelectcategory: " Kategorinizle başlayın",
    categoriesmainBeyourowntailor: "Kendi terziniz olun",
    categoriesmainSearch: "Anahtar kelime ile ara",
    categoriesmainWhatyoulikecustomize: "Kişiselleştirmeye buradan başlayın",
    categoriesmainMen: "Erkekler",
    categoriesmainWomen: "Kadınlar",
    categoriesmainDashboard: "Gösterge Tablosu",
    categoriesmainAddcategories: "Kategori ekle",
    categoriesmainAddmeasurment: "Ölçüm ekle",
    categoriesmainVieworders: "Siparişleri Görüntüle",
    categoriesmainViewmessages: "Mesajları Görüntüle",
    categoriesmainLatestordersnoti: "En son sipariş bildirimleri:",
    categoriesmainYouGotOrderfrom: "Yeni bir siparişiniz var",
    categoriesmainNoOrderFound: "Sipariş bulunamadı",
    categoriesmainLatestChats: "En son sohbetler",
    categoriesmainNoChatsFound: "Sohbet bulunamadı",
    categoriesmainOrderCompleted: "Sipariş tamamlandı",
    categoriesmainTotalEarnings: "Toplam kazanç",
    categoriesmainNewMessages: "Yeni mesajlar",
    categoriesmainOrderHistory: "Sipariş geçmişi",
    categoriesmainView: "Görüntüle",
    categoriesmainSetting: "Ayarlar",

    categorydetailAddcompletemeasurement:
      "Lütfen eksiksiz ölçümleri aşağıdaki bölüme ekleyin",
    categorydetailSelectsubategory:
      "Lütfen altından alt kategori verilerini seçin",
    categorydetailAdded: "Eklendi",
    categorydetailCustomizer: "özelleştirici",
    categorydetailItemaddedcart: "Ürün sepete eklendi.",
    categorydetailRequiredmeasurement: "Gerekli ölçüm:",
    categorydetailAddmeasurements: "Ölçüm ekle",
    categorydetailAddcart: "Sepete Ekle",
    categorydetailTypeValue: "Değeri buraya yazın",
    categorydetailInstruction: "Talimat",
    categorydetailNoCustomizerAvailable: "Özelleştirici Yok",

    chatscreenHelpSupport: "Yardım ve destek",
    chatscreenEntermessage: "Mesajı girin",

    orderhistoryfirst_name: "Ad:",
    orderhistorylast_name: "Soyadı:",
    orderhistoryPhone: "Telefon no:",
    orderhistoryAddress: "Adres:",
    orderhistoryContactSeller: "Satıcıyla iletişime geç:",
    orderhistoryChat: "Şimdi sohbet et",
    orderhistoryMeasurments: " Ölçümler :",
    orderhistoryHeader: "Sipariş geçmişi",

    orderlistfirst_name: "Ad:",
    orderlistlast_name: "Soyadı:",
    orderlistPhone: "Telefon no:",
    orderlistAddress: "Adres:",
    orderlistPrice: "Fiyat:",
    orderlistDate: "Tarih:",
    orderlistUpdatestatus: "Durumu yönet:",
    orderlistMeasurments: " Ölçüler :",
    orderlistStatusUpdated: "Durum güncellendi!",
    orderlistStatusupdatedsuccessfully: "Sipariş durumu güncellendi!",
    orderlistHeader: "Sipariş listesi",
    orderlistNothanks: "Hayır, teşekkürler",
    orderlistPayattention: "Dikkat edin !!!",
    orderlistPleaseUpdatestatusorder:
      "Bu siparişin durumunu güncellemek için lütfen aşağıdan bir seçenek seçin:",
    orderlistProcessing: "İşleniyor",
    orderlistCompleted: "Tamamlandı",
    orderlistCancelled: "İptal edildi",
    orderlistPending: "Beklemede",
    orderlistCompleteMsg: "Sipariş tamamlandı",
    orderlistOrderDetails: " Sipariş detayları:",

    authPleaseaddproperly: "Lütfen verileri doğru şekilde ekleyin.",
    authNouserrecordmaydeleted:
      "Bu tanımlayıcıya karşılık gelen kullanıcı kaydı yok. Kullanıcı silinmiş olabilir.",
    authAddemail: "Lütfen e-posta ekleyin.",

    settingHeading: "Ayarlar",
    settingcurrency: "Para Birimi Ayarı :",
    settingselectcurrency: "Para Birimi Seç",
    settingsave: "Kaydet",
    settingChangeLanguage: "Dili Değiştir",
    settingLanguages: "Diller",
    settingGeneralEmailsettings: "Genel E-posta ayarları",
    settingEmailSetting: "E-posta Ayarı :",
    settingAddLogo: "Logo ekle",
    settingapi_key: "API anahtarı",
    settingproduct_title: "Ürün başlığı",
    settingOrderPlacedTemplate: "Sipariş verilmiş şablon",
    settingDynamicparams: "Dinamik parametreler:",
    settingParamsOne: "%name%",
    settingParamsTwo: "%order_id%",
    settingParamsThree: "%category_id%",
    settingParamsName: "Bu, müşteri adını göstermek için kullanılacaktır",
    settingParamsorder_id:
      "Bu, sipariş kimliğini göstermek için kullanılacaktır",
    settingParamsCategory:
      "Bu, takım elbise gibi kategorileri göstermek için kullanılacaktır",
    settingEmailSubject: "E-posta Konusu",
    settingEmailContent: "E-posta içeriği",
    settingProcessingOrderTemplate: "Sipariş şablonu işleniyor",
    settingCompleteOrderTemplate: "Tam sipariş şablonu",
    settingCancelledOrderTemplate: "İptal edilen sipariş şablonu",
    settingPleaseSelectchangeanguage:
      "Dili değiştirmek için lütfen aşağıdan bir seçenek belirleyin",
    settingselectedcurrency: "Seçilen para birimi :",
    settingselectedLanguage: "Seçilen Dil :",

    cartNoReacordFound: "Kayıt yok, yenilemek için sürükleyin",
    historyNoReacordFound: "Kayıt Bulunamadı",
    pendingOrder: "Bekleyen Siparişler",
    processingorders: "Siparişleri İşleme",
    completedorders: "Tamamlanan Siparişler",
    cancelledorders: "İptal Edilen Siparişler",
  },
  ko: {
    Submit: "제출",
    Oops: "죄송합니다",
    AddThumbnail: "썸네일 추가",
    Search: "검색",
    male: "남성",
    female: "여성",
    Edit: "편집",
    Delete: "삭제",
    AddNow: "지금 추가",
    Updated: "업데이트됨!",
    AddMore: "더 추가",

    AppStackCategories: "카테고리",
    AppStackProfile: "프로필",
    AppStackCart: "카트",
    AppStackHistory: "역사",

    onboardingDescription:
      " Tailoron은 온라인 맞춤 제작을 위한 최고의 앱입니다. 무제한 사용자 지정, 온라인 디자인 및 제출, 이메일 알림, 각 주문에 대한 측정 제출 등을 포함한 우수한 기능이 풍부합니다.",
    onboardingDone: "시작하자",
    onboardingheader: "귀하의 개성을 맞춤화합니다",

    signupEmail: "이메일",
    signupPassword: "비밀번호",
    signupCpassword: "비밀번호 확인",
    signupSignup: "가입",
    signupByregisteringconfirm:
      "등록함으로써 귀하는 당사의 동의를 확인하는 것입니다",
    signupTermsservice: " 서비스 약관",
    signupand: "그리고",
    signupPrivacyPolicy: "개인 정보 보호 정책",
    signupHaveaccountsignin: "계정이 있습니까? 로그인하십시오",
    signupSignin: "지금 로그인 ",
    signupTermsserviceAlert: "조건을 클릭했습니다!",

    loginEmail: "이메일 주소",
    loginPassword: "비밀번호",
    loginSignIn: "로그인",
    loginForgotpassword: "비밀번호를 잊으셨습니까?",
    loginNotmember: "아직 회원이 아니 신가요 ?",
    loginRegister: "지금 등록",

    forgetpasswordEmail: "이메일",
    forgetpasswordresetnow: "지금 재설정",
    forgetpasswordHaveaccount: "계정이 있습니까? 로그인하십시오",
    forgetpasswordSignin: "지금 로그인 ",

    profileUpdated: "프로필이 업데이트되었습니다!",
    profilePublishedsuccessfully: "프로필이 게시되었습니다!",
    profileAddcompletedata: "완전한 데이터를 추가하십시오.",
    profilefirst_name: "이름",
    profilelast_name: "성",
    profilePhone: "전화번호",
    profileAddress: "주소",
    profileBillingShipping: "청구 및 배송 세부 정보:",
    profileCountry: "국가",
    profileCity: "도시",
    profileState: "상태",
    profileZip: "우편번호",
    profileEmail: "이메일",
    profileUpdateProfie: "프로필 업데이트",
    profileAddproDet: "프로필 세부 정보 추가",
    profileSetting: "프로필 설정",

    categoriesAlreadyadded: "카테고리가 이미 추가되었습니다.",
    categoriesPleaseselect: "카테고리를 선택하십시오",
    categoriesCategoryadded: "카테고리가 추가되었습니다!",
    categoriesAddedsuccessfully: "카테고리가 추가되었습니다!",
    categoriesCategoryDeleted: "성공!",
    categoriesDeletedsuccessfully: "성공적으로 업데이트되었습니다!",
    categoriesSomethingwrongpostfirestore:
      "게시물을 Firestore로 업데이트하는 중에 문제가 발생했습니다.",
    categoriesPleaseinsertcompletedata: "완전한 데이터를 삽입하십시오",
    categoriesSelectgender: "성별 선택",
    categoriesAddcategories: "카테고리 추가",
    categoriesSelectcategory: "카테고리 선택",
    categoriesAddmorecategories: "목록에 없습니까? 새 카테고리 추가",
    categoriesAddtolist: "목록에 추가",
    categoriesPleaseselectcategories: " 카테고리를 선택하세요",
    categoriessavechanges: " 변경 사항 저장",
    categoriesAlreadyaddedcategories: "추가된 카테고리",
    categoriesmeasurements: "측정값: ",
    categoriesAddsteps: "하위 카테고리 추가",
    categoriestitle: "하위 카테고리 제목",
    categoriesdescription: "하위 카테고리 설명",
    categoriesThumbnailast_name: "썸네일 이름",
    categoriesAddfullimage: "전체 이미지 추가",
    categoriesGeneratelist: "목록에 추가",
    categoriesAddapparel_steps: "메인 카테고리 추가",
    categoriesTitle: "제목",
    categoriesSelectmeasurements: "측정값 선택",
    categoriesTypeheresearch: "검색하려면 여기에 입력하십시오...",
    categoriesSelectmeasurement: "측정 선택:",
    categoriesChoosemeasurements: "측정값 선택",
    categoriesAddnew: "새 항목 추가",
    categoriesDelete: "삭제",
    categoriesEdit: "편집",

    addMeasurementadded: "측정이 추가되었습니다!",
    addMeasurementAddedsuccessfully: "측정값이 추가되었습니다!",
    addMeasurementPleaseaddcompletedata: "완전한 데이터를 추가하십시오.",
    addMeasurementEditpressed: "편집 누름",
    addMeasurementMygender: "내 성별",
    addMeasurementMeasurementdeleted: "측정값이 삭제되었습니다!",
    addMeasurementmeasurementsdeletedsuccessfully: "측정값이 삭제되었습니다!",
    addMeasurementAddmeasurement: "측정 추가",
    addMeasurementTitle: "제목",
    addMeasurementDescription: "설명",
    addMeasurementvideo_link: "동영상 링크",
    addmeasurementselectsize: "크기 선택",
    addMeasurementWatchvideo: "동영상 보기",
    addmeasurementMeasureIn: "측정 위치:",
    addmeasurementsizecm: "크기(cm)",
    addmeasurementsizeinch: "크기(인치)",

    addnewcategoryCategoryalreadyaddsamename:
      "카테고리가 이미 같은 이름으로 추가되었습니다.",
    addnewcategoryCategoryadded: "카테고리가 추가되었습니다!",
    addnewcategoryCategoryaddedsuccessfully: "카테고리가 추가되었습니다!",
    addnewcategoryPleaseaddcompldata: "완전한 데이터를 추가하십시오.",
    addnewcategoryAddnewcategory: "새 카테고리 추가",
    addnewcategoryTitle: "제목",
    addnewcategoryCategorieslist: "카테고리 목록",
    addnewcategoryEditcategory: "카테고리 편집",
    addnewcategoryCategoriesupdate: "카테고리 업데이트됨",
    addnewcategoryupdatedcategory: "카테고리가 업데이트되었습니다!",
    addnewcategoryCategoriesdelete: "카테고리 삭제",
    addnewcategorydeletedcategory: "카테고리가 삭제되었습니다!",

    cartOrderplaced: "주문 완료!",
    cartOrderplacedsuccessfully: "주문이 완료되었습니다!",
    cartCart: "장바구니",
    cartPending: "보류 중",
    cartPrice: "가격:",
    cartViewdetails: "세부정보 보기",
    cartOrderdetails: "주문 내역",
    cartfirst_name: "이름:",
    cartlast_name: "성:",
    cartphone_number: "전화번호:",
    cartAddress: "주소:",
    cartMeasurments: "측정:",
    cartProceedorder: "주문 진행",

    categoriesmainGreat: "훌륭한",
    categoriesmainYounowadmin: "이제 관리자입니다.",
    categoriesmainNothanks: "아니요, 감사합니다",
    categoriesmainYesproceed: "예, 진행합니다",
    categoriesmainPayattention: "주의!!!",
    categoriesmainDoyoumakeaccountadmin:
      "이 계정을 관리자 계정으로 만드시겠습니까?",
    categoriesmainSelectcategory: " 카테고리로 시작",
    categoriesmainBeyourowntailor: "나만의 재단사가 되십시오",
    categoriesmainSearch: "키워드로 검색",
    categoriesmainWhatyoulikecustomize: "여기에서 사용자 정의 시작",
    categoriesmainMen: "남성",
    categoriesmainWomen: "여성",
    categoriesmainDashboard: "대시보드",
    categoriesmainAddcategories: "카테고리 추가",
    categoriesmainAddmeasurment: "측정 추가",
    categoriesmainVieworders: "주문 보기",
    categoriesmainViewmessages: "메시지 보기",
    categoriesmainLatestordersnoti: "최근 주문 알림:",
    categoriesmainYouGotOrderfrom: "새로운 주문을 받았습니다 . ",
    categoriesmainNoOrderFound: "주문을 찾을 수 없음",
    categoriesmainLatestChats: "최신 채팅",
    categoriesmainNoChatsFound: "채팅을 찾을 수 없음",
    categoriesmainOrderCompleted: "주문 완료",
    categoriesmainTotalEarnings: "총 수입",
    categoriesmainNewMessages: "새 메시지",
    categoriesmainOrderHistory: "주문 내역",
    categoriesmainView: "보기",
    categoriesmainSetting: "설정",

    categorydetailAddcompletemeasurement:
      "아래에 전체 측정값을 추가하십시오 . ",
    categorydetailSelectsubategory: "하위 카테고리 데이터를 선택하십시오",
    categorydetailAdded: "추가됨",
    categorydetailCustomizer: "사용자 정의",
    categorydetailItemaddedcart: "장바구니에 추가된 항목입니다.",
    categorydetailRequiredmeasurement: "필요한 측정값:",
    categorydetailAddmeasurements: "측정 추가",
    categorydetailAddcart: "장바구니에 담기",
    categorydetailTypeValue: "여기에 값 입력",
    categorydetailInstruction: "지시",
    categorydetailNoCustomizerAvailable: "사용 가능한 사용자 지정 도구 없음",

    chatscreenHelpSupport: "도움말 및 지원",
    chatscreenEntermessage: "메시지 입력",

    orderhistoryfirst_name: "이름:",
    orderhistorylast_name: "성:",
    orderhistoryPhone: "전화번호:",
    orderhistoryAddress: "주소:",
    orderhistoryContactSeller: "판매자에게 연락하기:",
    orderhistoryChat: "지금 채팅",
    orderhistoryMeasurments: "측정:",
    orderhistoryHeader: "주문 내역",

    orderlistfirst_name: "이름:",
    orderlistlast_name: "성:",
    orderlistPhone: "전화번호:",
    orderlistAddress: "주소:",
    orderlistPrice: "가격:",
    orderlistDate: "날짜:",
    orderlistUpdatestatus: "상태 관리:",
    orderlistMeasurments: "측정:",
    orderlistStatusUpdated: "상태가 업데이트되었습니다!",
    orderlistStatusupdatedsuccessfully: "주문 상태가 업데이트되었습니다!",
    orderlistHeader: "주문 목록",
    orderlistNothanks: "아니요, 감사합니다",
    orderlistPayattention: "주의!!!",
    orderlistPleaseUpdatestatusorder:
      "이 주문의 상태를 업데이트하려면 아래 옵션을 선택하십시오:",
    orderlistProcessing: "처리 중",
    orderlistCompleted: "완료",
    orderlistCancelled: "취소됨",
    orderlistPending: "보류 중",
    orderlistCompleteMsg: "주문 완료",
    orderlistOrderDetails: " 주문 세부정보:",

    authPleaseaddproperly: "데이터를 올바르게 추가하십시오.",
    authNouserrecordmaydeleted:
      "이 식별자에 해당하는 사용자 기록이 없습니다. 사용자가 삭제되었을 수 있습니다.",
    authAddemail: "이메일을 추가하세요.",

    settingHeading: "설정",
    settingcurrency: "통화 설정 :",
    settingselectcurrency: "통화 선택",
    settingsave: "저장",
    settingChangeLanguage: "언어 변경",
    settingLanguages: "언어",
    settingGeneralEmailsettings: "일반 이메일 설정",
    settingEmailSetting: "이메일 설정 :",
    settingAddLogo: "로고 추가",
    settingapi_key: "API 키",
    settingproduct_title: "제품 제목",
    settingOrderPlacedTemplate: "주문된 템플릿",
    settingDynamicparams: "동적 매개변수:",
    settingParamsOne: "%name%",
    settingParamsTwo: "%order_id%",
    settingParamsThree: "%category_id%",
    settingParamsName: "이것은 고객 이름을 표시하는 데 사용됩니다.",
    settingParamsorder_id: "주문 ID를 표시하는 데 사용됩니다",
    settingParamsCategory:
      "이것은 슈트와 같은 카테고리를 표시하는 데 사용됩니다",
    settingEmailSubject: "이메일 제목",
    settingEmailContent: "이메일 내용",
    settingProcessingOrderTemplate: "주문 템플릿 처리",
    settingCompleteOrderTemplate: "주문 템플릿 완성",
    settingCancelledOrderTemplate: "취소된 주문 템플릿",
    settingPleaseSelectchangeanguage:
      "언어를 변경하려면 아래 옵션을 선택하세요.",
    settingselectedcurrency: "선택한 통화 :",
    settingselectedLanguage: "선택한 언어 :",

    cartNoReacordFound: "기록이 없습니다. 새로고침하려면 드래그하세요.",
    historyNoReacordFound: "기록을 찾을 수 없습니다",
    pendingOrder: "주문을 보류",
    processingorders: "주문 처리",
    completedorders: "완료된 주문",
    cancelledorders: "취소된 주문",
  },
  fr: {
    Submit: "Soumettre",
    Oops: "Oups",
    AddThumbnail: "Ajouter une miniature",
    Search: "Rechercher",
    male: "Mâle",
    female: "Femelle",
    Edit: "Modifier",
    Delete: "Supprimer",
    AddNow: "Ajouter maintenant",
    Updated: "Actualisé!",
    AddMore: "Ajouter plus de",

    AppStackCategories: "Catégories",
    AppStackProfile: "Profil",
    AppStackCart: "Chariot",
    AppStackHistory: "Histoire",

    onboardingDescription:
      " Tailoron est une application de premier plan pour la personnalisation en ligne. Elle est enrichie d'excellentes fonctionnalités, notamment des personnalisateurs illimités, une conception et une soumission en ligne, des notifications par e-mail, la soumission de mesures pour chaque commande et bien plus encore. ",
    onboardingDone: " Commençons ",
    onboardingheader: "Nous personnalisons votre personnalité",

    signupEmail: "Email",
    signupPassword: "Mot de passe",
    signupCpassword: "Confirmer le mot de passe",
    signupSignup: "Inscrivez-vous",
    signupByregisteringconfirm:
      "En vous inscrivant, vous confirmez que vous acceptez notre",
    signupTermsservice: " Conditions d'utilisation",
    signupand: "et",
    signupPrivacyPolicy: "Politique de confidentialité",
    signupHaveaccountsignin: "Avez-vous un compte ? Connectez-vous",
    signupSignin: " Connectez-vous maintenant",
    signupTermsserviceAlert: "Termes cliqués !",

    loginEmail: "Adresse e-mail",
    loginPassword: "Mot de passe",
    loginSignIn: "Connexion",
    loginForgotpassword: "Mot de passe oublié ?",
    loginNotmember: "Pas encore membre ?",
    loginRegister: " Inscrivez-vous maintenant",

    forgetpasswordEmail: "Email",
    forgetpasswordresetnow: "Réinitialiser maintenant",
    forgetpasswordHaveaccount: "Avez-vous un compte ? Connectez-vous",
    forgetpasswordSignin: " Connectez-vous maintenant",

    profileUpdated: "Profil mis à jour !",
    profilePublishedsuccessfully: "Votre profil a été publié !",
    profileAddcompletedata: "Veuillez ajouter des données complètes.",
    profilefirst_name: "Prénom",
    profilelast_name: "Nom",
    profilePhone: "N° de téléphone.",
    profileAddress: "Adresse",
    profileBillingShipping: " Détails de facturation et d'expédition :",
    profileCountry: "Pays",
    profileCity: "Ville",
    profileState: "Etat",
    profileZip: "Code postal",
    profileEmail: "Email",
    profileUpdateProfie: "Mettre à jour le profil",
    profileAddproDet: "Ajouter les détails du profil",
    profileSetting: " Paramètre de profil",

    categoriesAlreadyadded: "Catégorie déjà ajoutée.",
    categoriesPleaseselect: "Veuillez sélectionner une catégorie",
    categoriesCategoryadded: "Catégorie ajoutée !",
    categoriesAddedsuccessfully: "Votre catégorie a été ajoutée !",
    categoriesCategoryDeleted: "Succès !",
    categoriesDeletedsuccessfully: "Mise à jour réussie !",
    categoriesSomethingwrongpostfirestore:
      "Une erreur s'est produite lors de la mise à jour de la publication vers firestore.",
    categoriesPleaseinsertcompletedata:
      "Veuillez insérer des données complètes",
    categoriesSelectgender: "Sélectionner le sexe",
    categoriesAddcategories: "Ajouter des catégories",
    categoriesSelectcategory: "Sélectionner une catégorie",
    categoriesAddmorecategories:
      "Pas dans la liste ? ajouter une nouvelle catégorie",
    categoriesAddtolist: "Ajouter à la liste",
    categoriesPleaseselectcategories: "Veuillez sélectionner une catégorie",
    categoriessavechanges: " Enregistrer les modifications",
    categoriesAlreadyaddedcategories: "Catégories ajoutées",
    categoriesmeasurements: "Mesures: ",
    categoriesAddsteps: "Ajouter des sous-catégories",
    categoriestitle: "Titre de la sous-catégorie",
    categoriesdescription: "Description de la sous-catégorie",
    categoriesThumbnailast_name: "Nom de la miniature",
    categoriesAddfullimage: "Ajouter une image complète",
    categoriesGeneratelist: "Ajouter à la liste",
    categoriesAddapparel_steps: "Ajouter des catégories principales",
    categoriesTitle: "Titre",
    categoriesSelectmeasurements: "Sélectionner les mesures",
    categoriesTypeheresearch: "Tapez ici pour rechercher ...",
    categoriesSelectmeasurement: "Sélectionner les mesures :",
    categoriesChoosemeasurements: "Choisissez les mesures",
    categoriesAddnew: "Ajouter nouveau",
    categoriesDelete: "Supprimer",
    categoriesEdit: "Editer",

    addMeasurementadded: "Mesure ajoutée !",
    addMeasurementAddedsuccessfully: "Les mesures ont été ajoutées !",
    addMeasurementPleaseaddcompletedata:
      "Veuillez ajouter des données complètes.",
    addMeasurementEditpressed: "Editer pressé",
    addMeasurementMygender: "Mon genre",
    addMeasurementMeasurementdeleted: "Mesure supprimée !",
    addMeasurementmeasurementsdeletedsuccessfully:
      "Les mesures ont été supprimées !",
    addMeasurementAddmeasurement: "Ajouter une mesure",
    addMeasurementTitle: "Titre",
    addMeasurementDescription: "Description",
    addMeasurementvideo_link: "Lien vidéo",
    addmeasurementselectsize: "Sélectionner la taille",
    addMeasurementWatchvideo: "Regarder la vidéo",
    addmeasurementMeasureIn: "Mesure dans :",
    addmeasurementsizecm: "Taille en (cm)",
    addmeasurementsizeinch: "Taille en (pouce)",

    addnewcategoryCategoryalreadyaddsamename:
      "Catégorie déjà ajoutée avec le même nom.",
    addnewcategoryCategoryadded: "Catégorie ajoutée !",
    addnewcategoryCategoryaddedsuccessfully: "La catégorie a été ajoutée !",
    addnewcategoryPleaseaddcompldata: "Veuillez ajouter des données complètes.",
    addnewcategoryAddnewcategory: "Ajouter une nouvelle catégorie",
    addnewcategoryTitle: "Titre",
    addnewcategoryCategorieslist: "Liste des catégories",
    addnewcategoryEditcategory: "Modifier la catégorie",
    addnewcategoryCategoriesupdate: "Catégories mises à jour",
    addnewcategoryupdatedcategory: "La catégorie a été mise à jour !",
    addnewcategoryCategoriesdelete: "Catégories supprimer",
    addnewcategorydeletedcategory: "La catégorie a été supprimée !",

    cartOrderplaced: "Commande passée !",
    cartOrderplacedsuccessfully: "Votre commande a été passée !",
    cartCart: "Panier",
    cartPending: "En attente",
    cartPrice: "Prix :",
    cartViewdetails: "Afficher les détails",
    cartOrderdetails: "Détails de la commande",
    cartfirst_name: "Prénom :",
    cartlast_name: "Nom :",
    cartphone_number: "N° de téléphone :",
    cartAddress: "Adresse :",
    cartMeasurments: "Mesures:",
    cartProceedorder: "Passer la commande",

    categoriesmainGreat: "Super",
    categoriesmainYounowadmin: "Vous êtes maintenant l'admin",
    categoriesmainNothanks: "Non, merci",
    categoriesmainYesproceed: "Oui, continuez",
    categoriesmainPayattention: "Faites attention !!!",
    categoriesmainDoyoumakeaccountadmin:
      "Voulez-vous créer ce compte en tant que compte administrateur ?",
    categoriesmainSelectcategory: "Commencez par votre catégorie ",
    categoriesmainBeyourowntailor: "Soyez votre propre tailleur",
    categoriesmainSearch: "Rechercher avec mot-clé",
    categoriesmainWhatyoulikecustomize: "Commencez votre personnalisation ici ",
    categoriesmainMen: "Homme",
    categoriesmainWomen: "Femmes",
    categoriesmainDashboard: "Tableau de bord",
    categoriesmainAddcategories: "Ajouter une catégorie",
    categoriesmainAddmeasurment: "Ajouter une mesure",
    categoriesmainVieworders: "Afficher les commandes",
    categoriesmainViewmessages: "Afficher les messages",
    categoriesmainLatestordersnoti: "Notifications des dernières commandes :",
    categoriesmainYouGotOrderfrom: "Vous avez une nouvelle commande de",
    categoriesmainNoOrderFound: "Aucune commande trouvée",
    categoriesmainLatestChats: "Derniers chats",
    categoriesmainNoChatsFound: "Aucun chat trouvé",
    categoriesmainOrderCompleted: "Commande terminée",
    categoriesmainTotalEarnings: "Total des gains",
    categoriesmainNewMessages: "Nouveaux messages",
    categoriesmainOrderHistory: "Historique des commandes",
    categoriesmainView: "View",
    categoriesmainSetting: "Paramètres",

    categorydetailAddcompletemeasurement:
      "Veuillez ajouter les mesures complètes sous ",
    categorydetailSelectsubategory:
      "Veuillez sélectionner les données des sous-catégories sous ",
    categorydetailAdded: "Ajouté",
    categorydetailCustomizer: "Personnalisateur",
    categorydetailItemaddedcart: "Article ajouté au panier.",
    categorydetailRequiredmeasurement: "Mesure requise :",
    categorydetailAddmeasurements: "Ajouter une mesure",
    categorydetailAddcart: "Ajouter au panier",
    categorydetailTypeValue: "Tapez la valeur ici",
    categorydetailInstruction: "Instruction",
    categorydetailNoCustomizerAvailable: "Aucun personnalisateur disponible",

    chatscreenHelpSupport: "Aide et support",
    chatscreenEntermessage: "Entrez le message",

    orderhistoryfirst_name: "Prénom :",
    orderhistorylast_name: "Nom :",
    orderhistoryPhone: "N° de téléphone :",
    orderhistoryAddress: "Adresse :",
    orderhistoryContactSeller: "Contacter le vendeur :",
    orderhistoryChat: "Discutez maintenant",
    orderhistoryMeasurments: "Mesures:",
    orderhistoryHeader: "Historique des commandes",

    orderlistfirst_name: "Prénom :",
    orderlistlast_name: "Nom :",
    orderlistPhone: "N° de téléphone :",
    orderlistAddress: "Adresse :",
    orderlistPrice: "Prix :",
    orderlistDate: "Date :",
    orderlistUpdatestatus: "Gérer le statut :",
    orderlistMeasurments: "Mesures:",
    orderlistStatusUpdated: "Statut mis à jour !",
    orderlistStatusupdatedsuccessfully:
      "Le statut de la commande a été mis à jour !",
    orderlistHeader: "Liste de commandes",
    orderlistNothanks: "Non, merci",
    orderlistPayattention: "Faites attention !!!",
    orderlistPleaseUpdatestatusorder:
      "Veuillez sélectionner une option ci-dessous pour mettre à jour le statut de cette commande :",
    orderlistProcessing: "Traitement",
    orderlistCompleted: "Terminé",
    orderlistCancelled: "Annulé",
    orderlistPending: "En attente",
    orderlistCompleteMsg: "Commande terminée",
    orderlistOrderDetails: " Détails de la commande :",

    authPleaseaddproperly: "Veuillez ajouter les données correctement.",
    authNouserrecordmaydeleted:
      "Aucun enregistrement utilisateur ne correspond à cet identifiant. L'utilisateur a peut-être été supprimé.",
    authAddemail: "Veuillez ajouter un e-mail.",

    settingHeading: " Paramètres ",
    settingcurrency: "Paramètre de devise :",
    settingselectcurrency: "Sélectionner la devise",
    settingsave: "Enregistrer",
    settingChangeLanguage: "Changer la langue",
    settingLanguages: "Langues",
    settingGeneralEmailsettings: "Paramètres généraux de messagerie",
    settingEmailSetting: "Paramètre de messagerie :",
    settingAddLogo: "Ajouter un logo",
    settingapi_key: "clé API",
    settingproduct_title: "Titre du produit",
    settingOrderPlacedTemplate: "Commander le modèle placé",
    settingDynamicparams: "Paramètres dynamiques :",
    settingParamsOne: "%name%",
    settingParamsTwo: "%order_id%",
    settingParamsThree: "%category_id%",
    settingParamsName: "Ceci sera utilisé pour afficher le nom du client",
    settingParamsorder_id:
      "Ceci sera utilisé pour afficher l'ID de la commande",
    settingParamsCategory:
      "ce sera utilisé pour afficher la catégorie comme suit",
    settingEmailSubject: "Objet de l'e-mail",
    settingEmailContent: "Contenu de l'e-mail",
    settingProcessingOrderTemplate: "Modèle de commande de traitement",
    settingCompleteOrderTemplate: "Modèle de commande complet",
    settingCancelledOrderTemplate: "Modèle de commande annulée",
    settingPleaseSelectchangeanguage:
      "Veuillez sélectionner une option ci-dessous pour changer la langue",
    settingselectedcurrency: "Devise sélectionnée :",
    settingselectedLanguage: "Langue sélectionnée :",

    cartNoReacordFound: "Aucun enregistrement, faites glisser pour actualiser",
    historyNoReacordFound: "Aucun Enregistrement Trouvé",
    pendingOrder: "Les ordres en attente",
    processingorders: "Traitement des commandes",
    completedorders: "Commandes terminées",
    cancelledorders: "Commandes annulées",
  },
  el: {
    Submit: "Υποβολή",
    Oops: "Ωχ",
    AddThumbnail: "Προσθήκη μικρογραφίας",
    Search: "Αναζήτηση",
    male: "Αρσενικό",
    female: "Γυναίκα",
    Edit: "Επεξεργασία",
    Delete: "Διαγραφή",
    AddNow: "Προσθήκη τώρα",
    Updated: "Ενημερώθηκε!",
    AddMore: "Πρόσθεσε περισσότερα",

    AppStackCategories: "Κατηγορίες",
    AppStackProfile: "Προφίλ",
    AppStackCart: "Καροτσάκι",
    AppStackHistory: "Ιστορία",

    onboardingDescription:
      "Tailoron είναι μια πρεμιέρα App για online Ράψιμο. Είναι εμπλουτισμένο με εξαιρετικά χαρακτηριστικά, όπως απεριόριστη προσαρμογής, σε απευθείας σύνδεση σχεδιασμό και την υποβολή, ειδοποιήσεις μέσω ηλεκτρονικού ταχυδρομείου, την υποβολή μέτρησης για κάθε παραγγελία και πολλά άλλα.",
    onboardingDone: "Ας ξεκινήσουμε",
    onboardingheader: "Προσαρμόζουμε την προσωπικότητά σας",

    signupEmail: "ΗΛΕΚΤΡΟΝΙΚΗ ΔΙΕΥΘΥΝΣΗ",
    signupPassword: "Κωδικός πρόσβασης",
    signupCpassword: "Επιβεβαίωση κωδικού πρόσβασης",
    signupSignup: "Εγγραφή",
    signupByregisteringconfirm:
      "Με την εγγραφή, επιβεβαιώνετε ότι αποδέχεστε μας",
    signupTermsservice: "Όροι υπηρεσίας",
    signupand: "και",
    signupPrivacyPolicy: "Πολιτική απορρήτου",
    signupHaveaccountsignin: "Έχετε λογαριασμό, Συνδεθείτε",
    signupSignin: "Σύνδεση τώρα",
    signupTermsserviceAlert: " Έγινε κλικ στους όρους!",

    loginEmail: "Διεύθυνση email",
    loginPassword: "Κωδικός πρόσβασης",
    loginSignIn: "Σύνδεση",
    loginForgotpassword: "Ξεχάσατε τον κωδικό πρόσβασης,",
    loginNotmember: "Δεν είστε ακόμη μέλος,",
    loginRegister: "Εγγραφή τώρα",

    forgetpasswordEmail: "Email",
    forgetpasswordresetnow: "Επαναφορά τώρα",
    forgetpasswordHaveaccount: "Έχετε λογαριασμό, Συνδεθείτε",
    forgetpasswordSignin: "Σύνδεση τώρα",

    profileUpdated: "Το προφίλ ενημερώθηκε!",
    profilePublishedsuccessfully: "Το προφίλ σας έχει δημοσιευτεί!",
    profileAddcompletedata: "Προσθέστε πλήρη δεδομένα.",
    profilefirst_name: "Όνομα",
    profilelast_name: "Επώνυμο",
    profilePhone: " Αριθμός τηλεφώνου.",
    profileAddress: "Διεύθυνση",
    profileBillingShipping: "Λεπτομέρειες χρέωσης και αποστολής:",
    profileCountry: "Χώρα",
    profileCity: "Πόλη",
    profileState: "Πολιτεία",
    profileZip: "Ταχυδρομικός κώδικας",
    profileEmail: "Email",
    profileUpdateProfie: "Ενημέρωση προφίλ",
    profileAddproDet: "Προσθήκη λεπτομερειών προφίλ",
    profileSetting: "Ρύθμιση προφίλ",

    categoriesAlreadyadded: "Η κατηγορία έχει ήδη προστεθεί.",
    categoriesPleaseselect: "Παρακαλώ επιλέξτε μια κατηγορία",
    categoriesCategoryadded: "Η κατηγορία προστέθηκε!",
    categoriesAddedsuccessfully: "Η κατηγορία σας έχει προστεθεί!",
    categoriesCategoryDeleted: "Επιτυχία!",
    categoriesDeletedsuccessfully: "Επιτυχής ενημέρωση!",
    categoriesSomethingwrongpostfirestore:
      "Κάτι πήγε στραβά με την ενημέρωση της ανάρτησης στο firestore.",
    categoriesPleaseinsertcompletedata: "Παρακαλώ εισάγετε πλήρη δεδομένα",
    categoriesSelectgender: "Επιλογή φύλου",
    categoriesAddcategories: "Προσθήκη κατηγοριών",
    categoriesSelectcategory: "Επιλογή κατηγορίας",
    categoriesAddmorecategories:
      "Δεν περιλαμβάνεται στη λίστα, προσθέστε νέα κατηγορία",
    categoriesAddtolist: "Προσθήκη στη λίστα",
    categoriesPleaseselectcategories: "Παρακαλώ επιλέξτε κατηγορίες",
    categoriessavechanges: "Αποθήκευση αλλαγών",
    categoriesAlreadyaddedcategories: "Προστέθηκαν Categories",
    categoriesmeasurements: "Μετρήσεις:",
    categoriesAddsteps: "Προσθήκη υποκατηγοριών",
    categoriestitle: "Τίτλος υποκατηγορίας",
    categoriesdescription: "Περιγραφή υποκατηγορίας",
    categoriesThumbnailast_name: "Όνομα μικρογραφίας",
    categoriesAddfullimage: "Προσθήκη πλήρους εικόνας",
    categoriesGeneratelist: "Προσθήκη στη λίστα",
    categoriesAddapparel_steps: "Προσθήκη κύριων κατηγοριών",
    categoriesTitle: "Τίτλος",
    categoriesSelectmeasurements: "Επιλογή μετρήσεων",
    categoriesTypeheresearch: "Πληκτρολογήστε εδώ για αναζήτηση ...",
    categoriesSelectmeasurement: "Επιλογή μετρήσεων:",
    categoriesChoosemeasurements: "Επιλογή μετρήσεων",
    categoriesAddnew: "Προσθήκη νέου",
    categoriesDelete: "Διαγραφή",
    categoriesEdit: "Επεξεργασία",

    addMeasurementadded: "Προστέθηκε μέτρηση!",
    addMeasurementAddedsuccessfully: "Προστέθηκαν μετρήσεις!",
    addMeasurementPleaseaddcompletedata: "Προσθέστε πλήρη δεδομένα.",
    addMeasurementEditpressed: "Επεξεργασία πιεσμένη",
    addMeasurementMygender: "Το φύλο μου",
    addMeasurementMeasurementdeleted: "Η μέτρηση διαγράφηκε!",
    addMeasurementmeasurementsdeletedsuccessfully: "Οι μετρήσεις διαγράφηκαν!",
    addMeasurementAddmeasurement: "Προσθήκη μέτρησης",
    addMeasurementTitle: "Τίτλος",
    addMeasurementDescription: "Περιγραφή",
    addMeasurementvideo_link: "Σύνδεσμος βίντεο",
    addmeasurementselectsize: "Επιλογή μεγέθους",
    addMeasurementWatchvideo: "Παρακολούθηση βίντεο",
    addmeasurementMeasureIn: "Μέτρο σε:",
    addmeasurementsizecm: "Μέγεθος σε (cm)",
    addmeasurementsizeinch: "Μέγεθος σε (ίντσα)",

    addnewcategoryCategoryalreadyaddsamename:
      "Η κατηγορία έχει ήδη προστεθεί με το ίδιο όνομα.",
    addnewcategoryCategoryadded: "Η κατηγορία προστέθηκε!",
    addnewcategoryCategoryaddedsuccessfully: "Η κατηγορία έχει προστεθεί!",
    addnewcategoryPleaseaddcompldata: "Προσθέστε πλήρη δεδομένα.",
    addnewcategoryAddnewcategory: "Προσθήκη νέας κατηγορίας",
    addnewcategoryTitle: "Τίτλος",
    addnewcategoryCategorieslist: "Λίστα κατηγοριών",
    addnewcategoryEditcategory: "Επεξεργασία κατηγορίας",
    addnewcategoryCategoriesupdate: "Οι κατηγορίες ενημερώθηκαν",
    addnewcategoryupdatedcategory: "Η κατηγορία έχει ενημερωθεί!",
    addnewcategoryCategoriesdelete: "Κατηγορίες διαγραφή",
    addnewcategorydeletedcategory: "Η κατηγορία διαγράφηκε!",

    cartOrderplaced: "Η παραγγελία έγινε!",
    cartOrderplacedsuccessfully: "Η παραγγελία σας έχει υποβληθεί!",
    cartCart: "Καλάθι",
    cartPending: "Σε εκκρεμότητα",
    cartPrice: "Τιμή:",
    cartViewdetails: "Προβολή λεπτομερειών",
    cartOrderdetails: "Λεπτομέρειες παραγγελίας",
    cartfirst_name: "Όνομα:",
    cartlast_name: "Επώνυμο:",
    cartphone_number: " Αριθμός τηλεφώνου:",
    cartAddress: "Διεύθυνση:",
    cartMeasurments: " Μετρήσεις :",
    cartProceedorder: "Συνεχίστε την παραγγελία",

    categoriesmainGreat: "Υπέροχο",
    categoriesmainYounowadmin: "Είστε πλέον ο διαχειριστής",
    categoriesmainNothanks: "Όχι, ευχαριστώ",
    categoriesmainYesproceed: "Ναι, προχωρήστε",
    categoriesmainPayattention: "Δώστε προσοχή !!!",
    categoriesmainDoyoumakeaccountadmin:
      "Θέλετε να κάνετε αυτόν τον λογαριασμό ως λογαριασμό διαχειριστή,",
    categoriesmainSelectcategory: "Ξεκινήστε με την κατηγορία σας",
    categoriesmainBeyourowntailor: "Γίνε ο δικός σου ράφτης",
    categoriesmainSearch: "Αναζήτηση με λέξη-κλειδί",
    categoriesmainWhatyoulikecustomize: "Ξεκινήστε την προσαρμογή σας εδώ",
    categoriesmainMen: "Άνδρες",
    categoriesmainWomen: "Γυναίκες",
    categoriesmainDashboard: "Πίνακας ελέγχου",
    categoriesmainAddcategories: "Προσθήκη κατηγορίας",
    categoriesmainAddmeasurment: "Προσθήκη μέτρησης",
    categoriesmainVieworders: "Προβολή παραγγελιών",
    categoriesmainViewmessages: "Προβολή μηνυμάτων",
    categoriesmainLatestordersnoti: "Ειδοποιήσεις τελευταίων παραγγελιών:",
    categoriesmainYouGotOrderfrom: "Έχετε μια νέα παραγγελία από",
    categoriesmainNoOrderFound: "Δεν βρέθηκε παραγγελία",
    categoriesmainLatestChats: "Τελευταίες συζητήσεις",
    categoriesmainNoChatsFound: "Δεν βρέθηκαν συζητήσεις",
    categoriesmainOrderCompleted: "Η παραγγελία ολοκληρώθηκε",
    categoriesmainTotalEarnings: "Συνολικά κέρδη",
    categoriesmainNewMessages: "Νέα μηνύματα",
    categoriesmainOrderHistory: "Ιστορικό παραγγελιών",
    categoriesmainView: "Προβολή",
    categoriesmainSetting: "Ρυθμίσεις",

    categorydetailAddcompletemeasurement:
      "Παρακαλώ προσθέστε πλήρεις μετρήσεις στην ενότητα",
    categorydetailSelectsubategory:
      "Παρακαλούμε επιλέξτε δεδομένα υποκατηγοριών κάτω από",
    categorydetailAdded: "Προστέθηκε",
    categorydetailCustomizer: "Εξατομικευτής",
    categorydetailItemaddedcart: "Στοιχείο προστέθηκε στο καλάθι.",
    categorydetailRequiredmeasurement: "Απαιτούμενη μέτρηση:",
    categorydetailAddmeasurements: "Προσθήκη μέτρησης",
    categorydetailAddcart: "Προσθήκη στο καλάθι",
    categorydetailTypeValue: "Πληκτρολογήστε την τιμή εδώ",
    categorydetailInstruction: "Οδηγίες",
    categorydetailNoCustomizerAvailable:
      "Δεν υπάρχει διαθέσιμο εργαλείο προσαρμογής",

    chatscreenHelpSupport: "Βοήθεια και υποστήριξη",
    chatscreenEntermessage: "Εισαγωγή μηνύματος",

    orderhistoryfirst_name: "Όνομα:",
    orderhistorylast_name: "Επώνυμο:",
    orderhistoryPhone: " Αριθμός τηλεφώνου:",
    orderhistoryAddress: "Διεύθυνση:",
    orderhistoryContactSeller: "Επικοινωνήστε με τον πωλητή:",
    orderhistoryChat: "Συνομιλία τώρα",
    orderhistoryMeasurments: " Μετρήσεις :",
    orderhistoryHeader: "Ιστορικό παραγγελιών",

    orderlistfirst_name: "Όνομα:",
    orderlistlast_name: "Επώνυμο:",
    orderlistPhone: " Αριθμός τηλεφώνου:",
    orderlistAddress: "Διεύθυνση:",
    orderlistPrice: "Τιμή:",
    orderlistDate: "Ημερομηνία:",
    orderlistUpdatestatus: "Διαχείριση κατάστασης:",
    orderlistMeasurments: " Μετρήσεις :",
    orderlistStatusUpdated: "Η κατάσταση ενημερώθηκε!",
    orderlistStatusupdatedsuccessfully:
      "Η κατάσταση παραγγελίας έχει ενημερωθεί!",
    orderlistHeader: "Λίστα παραγγελιών",
    orderlistNothanks: "Όχι, ευχαριστώ",
    orderlistPayattention: "Δώστε προσοχή !!!",
    orderlistPleaseUpdatestatusorder:
      "Ορίστε μια επιλογή παρακάτω για να ενημερώσετε την κατάσταση αυτής της παραγγελίας:",
    orderlistProcessing: "Επεξεργασία",
    orderlistCompleted: "Ολοκληρώθηκε",
    orderlistCancelled: "Ακυρώθηκε",
    orderlistPending: "Σε εκκρεμότητα",
    orderlistCompleteMsg: "Η παραγγελία ολοκληρώθηκε",
    orderlistOrderDetails: "Λεπτομέρειες παραγγελίας:",

    authPleaseaddproperly: "Παρακαλώ προσθέστε τα δεδομένα σωστά.",
    authNouserrecordmaydeleted:
      "Δεν υπάρχει εγγραφή χρήστη που να αντιστοιχεί σε αυτό το αναγνωριστικό. Ο χρήστης ενδέχεται να έχει διαγραφεί.",
    authAddemail: "Προσθέστε email.",

    settingHeading: "Ρυθμίσεις",
    settingcurrency: "Ρύθμιση νομίσματος:",
    settingselectcurrency: "Επιλογή νομίσματος",
    settingsave: "Αποθήκευση",
    settingChangeLanguage: "Αλλαγή γλώσσας",
    settingLanguages: "Γλώσσες",
    settingGeneralEmailsettings: "Γενικές ρυθμίσεις email",
    settingEmailSetting: "Ρύθμιση email:",
    settingAddLogo: "Προσθήκη λογότυπου",
    settingapi_key: "Κλειδί API",
    settingproduct_title: "Τίτλος προϊόντος",
    settingOrderPlacedTemplate: "Πρότυπο παραγγελίας",
    settingDynamicparams: "Δυναμικές παράμετροι:",
    settingParamsOne: "%name%",
    settingParamsTwo: "%order_id%",
    settingParamsThree: "%category_id%",
    settingParamsName:
      "Αυτό θα χρησιμοποιηθεί για την εμφάνιση του ονόματος πελάτη",
    settingParamsorder_id:
      "Αυτό θα χρησιμοποιηθεί για την εμφάνιση αναγνωριστικού παραγγελίας",
    settingParamsCategory:
      "Αυτό θα χρησιμοποιηθεί για την εμφάνιση κατηγορίας όπως ταιριάζει",
    settingEmailSubject: "Θέμα ηλεκτρονικού ταχυδρομείου",
    settingEmailContent: "Περιεχόμενο ηλεκτρονικού ταχυδρομείου",
    settingProcessingOrderTemplate: "Πρότυπο παραγγελίας επεξεργασίας",
    settingCompleteOrderTemplate: "Πλήρες πρότυπο παραγγελίας",
    settingCancelledOrderTemplate: "Πρότυπο παραγγελίας που ακυρώθηκε",
    settingPleaseSelectchangeanguage:
      "Ορίστε μια από τις παρακάτω επιλογές για να αλλάξετε τη γλώσσα",
    settingselectedcurrency: "Επιλεγμένο νόμισμα :",
    settingselectedLanguage: "Επιλεγμένη γλώσσα :",

    cartNoReacordFound: "Χωρίς εγγραφή, σύρετε για ανανέωση",
    historyNoReacordFound: "Δεν Βρέθηκε Αρχείο",
    pendingOrder: "Εκκρεμείς παραγγελίες",
    processingorders: "Επεξεργασία παραγγελιών",
    completedorders: "Ολοκληρωμένες παραγγελίες",
    cancelledorders: "Ακυρωμένες παραγγελίες",
  },
});
export default strings;
